fix: restore cicd.yaml from main (no diff)

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -121,6 +121,8 @@ jobs:
         if: always()
         shell: bash
         run: |
+          WHITELIST=".github/actions/jfrog-xray-scan/tolerated_violations.txt"
+
           echo "Comparing with last scan file: ./last-main-scan.json"
 
           echo "New violations since last scan:"
@@ -128,14 +130,30 @@ jobs:
           jq -r '.[].violations[]?.issue_id' "$SCAN_JSON" > new.txt
 
           NEW_VIOLATIONS=$(comm -13 <(sort old.txt) <(sort new.txt))
+          REMOVED_VIOLATIONS=$(comm -13 <(sort new.txt) <(sort old.txt))
+
+          FAIL=0
 
           if [ -n "$NEW_VIOLATIONS" ]; then
             echo "New violations found:"
             echo "$NEW_VIOLATIONS"
-            exit 1
+            echo "Checking new violations against whitelist..."
+              while read -r violation; do
+                if ! grep -q "$violation" "$WHITELIST"; then
+                  echo "New violation not whitelisted: $violation"
+                  FAIL=1
+                fi
+              done <<< "$NEW_VIOLATIONS"
+
+              if [ "$FAIL" -eq 1 ]; then
+                echo "❌ Failing due to unwhitelisted new violations."
+                exit 1
+              fi
+          elif [ -n "$REMOVED_VIOLATIONS" ]; then
+            echo "The following violations were eliminated: $REMOVED_VIOLATIONS."
           else
             echo "No new violations found."
-          fi
+          fi  
 
   # Build and test Ark itself.
   build-and-test-ark:
@@ -219,6 +237,12 @@ jobs:
           artifact-folder: ark-api/unit-tests
           artifact-suffix: ark-api-unit
 
+      - uses: ./.github/actions/collect-coverage
+        with:
+          source-path: services/ark-dashboard/ark-dashboard/coverage/
+          artifact-folder: ark-dashboard/unit-tests
+          artifact-suffix: ark-dashboard-unit
+
   build-containers:
     needs: [setup-container-cache-registry, build-libs]
     runs-on: ubuntu-24.04
@@ -285,7 +309,6 @@ jobs:
           platforms: linux/amd64
           push: true
           prebuild: ${{ matrix.prebuild }}
-
 
   build-libs:
     runs-on: ubuntu-24.04
